# GENERATED by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest 88b7c615aa77)
"""Per-operation versioning-policy state embedded at generation time."""

EMBEDDED_MANIFEST = {
    "OntologyEntities": {
        "kind": "Query"
    },
    "OntologyEntity": {
        "kind": "Query"
    },
    "OntologyDescribe": {
        "kind": "Query"
    },
    "OntologyRows": {
        "kind": "Query"
    },
    "OntologyQuery": {
        "kind": "Query"
    },
    "OntologyAggregate": {
        "kind": "Query"
    },
    "OntologyStats": {
        "kind": "Query"
    },
    "OntologySimilar": {
        "kind": "Query"
    },
    "OntologyFollowLink": {
        "kind": "Query"
    },
    "OntologyFollowIncomingLink": {
        "kind": "Query"
    },
    "OntologyFastLookups": {
        "kind": "Query"
    },
    "OntologyRecordCapabilities": {
        "kind": "Query"
    },
    "PreviewOntologyAction": {
        "kind": "Query"
    },
    "ExecuteOntologyAction": {
        "kind": "Mutation"
    },
    "OntologyActionExecutions": {
        "kind": "Query"
    },
    "OntologyAddRow": {
        "kind": "Mutation"
    },
    "OntologyAddRows": {
        "kind": "Mutation"
    },
    "OntologyUpdateRow": {
        "kind": "Mutation"
    },
    "OntologyDeleteRow": {
        "kind": "Mutation"
    },
    "ProjectDatasets": {
        "kind": "Query"
    },
    "QueryDataset": {
        "kind": "Query"
    },
    "ProjectSources": {
        "kind": "Query"
    },
    "PlatformSourceRows": {
        "kind": "Query"
    },
    "PlatformSourceObjects": {
        "kind": "Query"
    },
    "PlatformSourceColumns": {
        "kind": "Query"
    },
    "MyOrganizations": {
        "kind": "Query"
    },
    "Projects": {
        "kind": "Query"
    },
    "MyWorkspace": {
        "kind": "Query"
    }
}

MANIFEST_HASH = "88b7c615aa77e420862d5992c859fe1ee350ca3a256f26410e7787ffeb964462"

MANIFEST_PROTOCOL_VERSION = "1"
